feat: Add oneshot service (#21)
* feat: Add oneshot service

* feat: add anchor and service entry on snap manifest

* feat: stop service before it fails

Due to the lack of connected interfaces, the service will fail if not
stopped.

* feat: disable services in case of interfaces not being connected

* feat: add missing interfaces and improve install hook

* doc: update usage instructions

* chore: add link to issue

---------

Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>

diff --git a/snap/hooks/install b/snap/hooks/install
--- a/snap/hooks/install
+++ b/snap/hooks/install
@@ -1,4 +1,14 @@
 #!/bin/bash -x
 
+# Because the interfaces aren't connected yet, the service will fail to start.
+if ! snapctl is-connected etc-default-grub ||
+  ! snapctl is-connected proc-device-tree-model ||
+  ! snapctl is-connected proc-irq ||
+  ! snapctl is-connected sys-kernel-irq ||
+  # ! snapctl is-connected cpu-control || # NOTE this will replace the two above
+  ! snapctl is-connected hardware-observe; then
+  snapctl stop --disable "$SNAP_NAME.rt-confd"
+fi
+
 # Put the default configuration in place
 cp "$SNAP"/config.yaml "$SNAP_COMMON"/config.yaml
